---
Parameters:
  SourceBucketName:
    Description: Enter source bucket name
    Type: String

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket 
    Properties:
      BucketName: !Ref SourceBucketName
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Ref SNSTopic
      VersioningConfiguration:
        Status: Enabled

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:    
      Subscription: 
        - Endpoint: !GetAtt LambdaRunGlueJob.Arn           
          Protocol: lambda
        - Endpoint: !GetAtt LambdaSaveS3Config.Arn            
          Protocol: lambda
      TopicName: SNSTopicForFilesBucket

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: SNSActions
            Effect: Allow
            Principal:
                AWS: "*"
            Action:
              - SNS:Publish
              - SNS:RemovePermission
              - SNS:SetTopicAttributes
              - SNS:DeleteTopic
              - SNS:ListSubscriptionsByTopic
              - SNS:GetTopicAttributes
              - SNS:AddPermission
              - SNS:Subscribe
            Resource: !Ref SNSTopic
            Condition:
                StringEquals:
                  AWS:SourceOwner: !Sub '${AWS::AccountId}'

          - Sid: S3Acsess
            Effect: Allow
            Principal: 
              Service: 
                - s3.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub '${AWS::AccountId}'
              ArnEquals:
                aws:SourceArn: !Sub arn:aws:s3:::${SourceBucketName}
      Topics:
        - !Ref SNSTopic

  LambdaExecutionRole1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSNSReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess    
              
  LambdaExecutionRole2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSNSReadOnlyAccess

  InvokeLambdaRunGlueJob:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref  LambdaRunGlueJob
      Principal: sns.amazonaws.com
      SourceArn: !Ref SNSTopic

  InvokeLambdaSaveS3Config:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref  LambdaSaveS3Config
      Principal: sns.amazonaws.com
      SourceArn: !Ref SNSTopic      

  LambdaRunGlueJob:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_run_glue_jobs.lambda_handler
      Description: Lambda function 
      Role: !GetAtt LambdaExecutionRole2.Arn
      Runtime: python3.12
      Code:
        S3Bucket: !Sub 'codebucket-${AWS::AccountId}'
        S3Key: lambda_run_glue_jobs.zip

  LambdaSaveS3Config:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_save_s3_config.lambda_handler
      Description: Lambda function 
      Role: !GetAtt LambdaExecutionRole1.Arn
      Runtime: python3.12
      Environment: 
        Variables:
          "TABLE_NAME": !Ref DynamoDBTable
      Code:
        S3Bucket: !Sub 'codebucket-${AWS::AccountId}'
        S3Key: lambda_save_s3_config.zip

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "s3file-config-table-${AWS::AccountId}"
      AttributeDefinitions:
        - AttributeName: object_key
          AttributeType: S
        - AttributeName: version_id
          AttributeType: S
      KeySchema:
        - AttributeName: object_key
          KeyType: HASH
        - AttributeName: version_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
